// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: csenums.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::ILRuntime.Protobuf;
using pbc = global::ILRuntime.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Csp {

  #region Enums
  /// <summary>
  ///========== enum define ==========
  /// </summary>
  public enum CSEnmPlayerAttr {
    /// <summary>
    /// 玩家局内基础属性枚举
    /// </summary>
    PlayerStatsNone = 0,
    /// <summary>
    /// 局外养成等级
    /// </summary>
    PlayerLevel = 1,
    /// <summary>
    /// 角色等级
    /// </summary>
    CharacterLevel = 2,
    /// <summary>
    /// 皮肤等级
    /// </summary>
    SkinLevel = 3,
    /// <summary>
    /// 攻击
    /// </summary>
    BaseDmg = 4,
    /// <summary>
    /// 防御
    /// </summary>
    Defence = 5,
    /// <summary>
    /// 生命
    /// </summary>
    MaxHp = 6,
    /// <summary>
    /// 护盾
    /// </summary>
    MaxShield = 7,
    /// <summary>
    /// 攻速
    /// </summary>
    AtkSpd = 8,
    /// <summary>
    /// 局内攻速
    /// </summary>
    Aspd = 9,
    /// <summary>
    /// 闪避
    /// </summary>
    DodgeLvl = 10,
    /// <summary>
    /// 局内闪避率
    /// </summary>
    Dodge = 11,
    /// <summary>
    /// 玩家额外命中
    /// </summary>
    ExtraAccuracy = 12,
    /// <summary>
    /// 暴击
    /// </summary>
    Crit = 13,
    /// <summary>
    /// 局内暴击概率
    /// </summary>
    CritRate = 14,
    /// <summary>
    /// 暴击伤害倍率
    /// </summary>
    CritDmgMulti = 15,
    /// <summary>
    /// 首领伤害增加
    /// </summary>
    ToBossExtraDmg = 16,
    /// <summary>
    /// 精英伤害增加
    /// </summary>
    ToEliteExtraDmg = 17,
    /// <summary>
    /// 小怪伤害增加
    /// </summary>
    ToMinionExtraDmg = 18,
    /// <summary>
    /// 微生物伤害增加
    /// </summary>
    ToPopcornExtraDmg = 19,
    /// <summary>
    /// 治疗效果
    /// </summary>
    ExtraRegen = 20,
    /// <summary>
    /// 冷却恢复
    /// </summary>
    CdReduce = 21,
    /// <summary>
    /// 额外伤害加成
    /// </summary>
    ExtraDmg = 22,
    /// <summary>
    /// 额外伤害减免
    /// </summary>
    ExtraDmgReduce = 23,
    /// <summary>
    /// 武器伤害加成
    /// </summary>
    NormalDmgAdd = 24,
    /// <summary>
    /// 武器伤害减免
    /// </summary>
    NormalDmgReduce = 25,
    /// <summary>
    /// 反击伤害加成
    /// </summary>
    CounterDmgAdd = 26,
    /// <summary>
    /// 反击伤害减免
    /// </summary>
    CounterDmgReduce = 27,
    /// <summary>
    /// 火元素伤害加成
    /// </summary>
    FireDmgAdd = 28,
    /// <summary>
    /// 风元素伤害加成
    /// </summary>
    WindDmgAdd = 29,
    /// <summary>
    /// 雷元素伤害加成
    /// </summary>
    ElectricDmgAdd = 30,
    /// <summary>
    /// 毒元素伤害加成
    /// </summary>
    PoisonDmgAdd = 31,
    /// <summary>
    /// 冰元素伤害加成
    /// </summary>
    IceDmgAdd = 32,
    /// <summary>
    /// 火元素伤害减免
    /// </summary>
    FireDmgReduce = 33,
    /// <summary>
    /// 风元素伤害减免
    /// </summary>
    WindDmgReduce = 34,
    /// <summary>
    /// 雷元素伤害减免
    /// </summary>
    ElectricDmgReduce = 35,
    /// <summary>
    /// 毒元素伤害减免
    /// </summary>
    PoisonDmgReduce = 36,
    /// <summary>
    /// 冰元素伤害减免
    /// </summary>
    IceDmgReduce = 37,
    /// <summary>
    /// 控制时间强化
    /// </summary>
    BuffExtraTime = 38,
    /// <summary>
    /// 控制概率强化
    /// </summary>
    BuffExtraProb = 39,
    /// <summary>
    /// 碰撞伤害加成
    /// </summary>
    BumpExtraDmg = 40,
    /// <summary>
    /// 碰撞伤害减免
    /// </summary>
    BumpDmgReduce = 41,
    /// <summary>
    /// 格挡概率
    /// </summary>
    BlockRate = 42,
    /// <summary>
    /// 格挡系数
    /// </summary>
    BlockDmgReduce = 43,
    /// <summary>
    /// 反弹
    /// </summary>
    ReboundRate = 44,
    /// <summary>
    /// 必杀技伤害
    /// </summary>
    UltimateDmgAdd = 45,
    /// <summary>
    /// 卡牌护盾上限
    /// </summary>
    ShieldBase = 46,
    /// <summary>
    /// 血量护盾加成
    /// </summary>
    HpBasedShieldMulti = 47,
    /// <summary>
    /// 环绕物伤害加成
    /// </summary>
    CircleDmgAdd = 48,
    /// <summary>
    /// 冲击波伤害加成
    /// </summary>
    AbsorbAtkDmgAdd = 49,
    /// <summary>
    /// 符文伤害加成
    /// </summary>
    PickUpDmgAdd = 50,
    /// <summary>
    /// 暴击精通
    /// </summary>
    CritMaster = 51,
    /// <summary>
    /// 元素伤害加成
    /// </summary>
    ElementDmgAdd = 52,
    /// <summary>
    /// 火元素穿透
    /// </summary>
    FirePenetrate = 53,
    /// <summary>
    /// 风元素穿透
    /// </summary>
    WindPenetrate = 54,
    /// <summary>
    /// 雷元素穿透
    /// </summary>
    ElectricPenetrate = 55,
    /// <summary>
    /// 毒元素穿透
    /// </summary>
    PoisonPenetrate = 56,
    /// <summary>
    /// 冰元素穿透
    /// </summary>
    IcePenetrate = 57,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmPlayerAttrMax = 58,
  }

  public enum CSEnmConditionParamterType {
    /// <summary>
    /// 玩家基础属性枚举
    /// </summary>
    ParamterTypeNone = 0,
    /// <summary>
    /// 主线挑战N次
    /// </summary>
    StageBattleCount = 1,
    /// <summary>
    /// 主线X关卡挑战N次
    /// </summary>
    StageChapterBattleCount = 2,
    /// <summary>
    /// 通过X关卡N波
    /// </summary>
    StageChapterFinishWave = 3,
    /// <summary>
    /// 通关主线N关
    /// </summary>
    StageChapter = 4,
    /// <summary>
    /// 通关主线N章
    /// </summary>
    StageRegionFinish = 5,
    /// <summary>
    /// 时空试炼挑战N次
    /// </summary>
    ExpeditionBattleCount = 6,
    /// <summary>
    /// 时空试炼通关N次
    /// </summary>
    ExpeditionWinCount = 7,
    /// <summary>
    /// 击败X类型bossN个
    /// </summary>
    BeatBossCount = 8,
    /// <summary>
    /// 角色等级达到N级
    /// </summary>
    RoleLevel = 9,
    /// <summary>
    /// 升级N次
    /// </summary>
    LevelUpCount = 10,
    /// <summary>
    /// 角色境界达到N
    /// </summary>
    RoleEvoLevel = 11,
    /// <summary>
    /// 巡逻加速N次
    /// </summary>
    HangUpSpeedUpCount = 12,
    /// <summary>
    /// 挂机领奖N次
    /// </summary>
    HangUpHarvestCount = 13,
    /// <summary>
    /// 挂机奖励累积获得金币N枚
    /// </summary>
    HangUpCoinCount = 14,
    /// <summary>
    /// 挑战日常本N次
    /// </summary>
    DungeonCount = 15,
    /// <summary>
    /// 挑战XX类日常本N次
    /// </summary>
    DungeonTypeCount = 16,
    /// <summary>
    /// 通过日常本N次
    /// </summary>
    DungeonFinishCount = 17,
    /// <summary>
    /// 通过XXid日常本N次
    /// </summary>
    DungeonIdfinishCount = 18,
    /// <summary>
    /// XXid元素龙战斗N次
    /// </summary>
    BattleCount = 19,
    /// <summary>
    /// 使用XXid元素龙通过X关N波
    /// </summary>
    WaveFinishElementDragon = 20,
    /// <summary>
    /// 使用XXid逆鳞技通过X关N波
    /// </summary>
    WaveFinishUltimateSkill = 21,
    /// <summary>
    /// 通关X关X波时长小于N
    /// </summary>
    WaveFinishTime = 22,
    /// <summary>
    /// 通过X关X波时血量不低于N
    /// </summary>
    WaveFinishHppercent = 23,
    /// <summary>
    /// 击杀XXid的boss的时长小于N
    /// </summary>
    StageHitBossTime = 24,
    /// <summary>
    /// 击杀XXid的bossN次
    /// </summary>
    StageHitBossCount = 25,
    /// <summary>
    /// 装备升级N次
    /// </summary>
    SlotUpNormal = 26,
    /// <summary>
    /// 装备精炼N次
    /// </summary>
    SlotUpRefine = 27,
    /// <summary>
    /// 穿戴X阶装备N件
    /// </summary>
    EquipedTierCount = 28,
    /// <summary>
    /// 穿戴X品质装备N件
    /// </summary>
    EquipedQualityCount = 29,
    /// <summary>
    /// 装备槽强化到X级N次
    /// </summary>
    SlotUpNormalLevel = 30,
    /// <summary>
    /// 装备槽精炼到X级N次
    /// </summary>
    SlotUpRefineLevel = 31,
    /// <summary>
    /// 装备槽精炼等级总和达到N
    /// </summary>
    SlotRefineLevels = 32,
    /// <summary>
    /// 共鸣XX关联宝物的星级和达到N
    /// </summary>
    ResonanceCardsStarSum = 33,
    /// <summary>
    /// 龙神共鸣激活N个
    /// </summary>
    ResonanceActiveCount = 34,
    /// <summary>
    /// 第X章熟练度达到N
    /// </summary>
    RegionExpPercent = 35,
    /// <summary>
    /// 获得XXid的熟练度N次
    /// </summary>
    SectionRegionExpCount = 36,
    /// <summary>
    /// 累积获得熟练度N点
    /// </summary>
    RegionExpCount = 37,
    /// <summary>
    /// 升级熟练度N次
    /// </summary>
    RegionExpLevelUpCount = 38,
    /// <summary>
    /// 熟练度商店购买N次
    /// </summary>
    RegionShopBuy = 39,
    /// <summary>
    /// 清空X章节所有商品N次
    /// </summary>
    RegionShopClean = 40,
    /// <summary>
    /// XXid元素龙N级
    /// </summary>
    ElementDragonLevel = 41,
    /// <summary>
    /// XXid元素龙N星
    /// </summary>
    ElementDragonStarLevel = 42,
    /// <summary>
    /// N条元素龙升至X级
    /// </summary>
    ElementDragonLevelReach = 43,
    /// <summary>
    /// N条元素龙升至X星
    /// </summary>
    ElementDragonStarReach = 44,
    /// <summary>
    /// 解锁N条元素龙
    /// </summary>
    ElementDragonActive = 45,
    /// <summary>
    /// 解锁N条X品质元素龙
    /// </summary>
    ElementDragonQualityActive = 46,
    /// <summary>
    /// 解锁终结技N个
    /// </summary>
    UltimateCardTypeCount = 47,
    /// <summary>
    /// 解锁N品质终结技N个
    /// </summary>
    UltimateQualityUnlock = 48,
    /// <summary>
    /// 终结技升到X星N个
    /// </summary>
    UltimateCardStarUpCount = 49,
    /// <summary>
    /// 解锁天赋N次
    /// </summary>
    TalentUnlock = 50,
    /// <summary>
    /// 解锁XX传承的所有天赋
    /// </summary>
    TalentDragonUnlock = 51,
    /// <summary>
    /// 激活XXid的天赋
    /// </summary>
    TalentUnlockOne = 52,
    /// <summary>
    /// 天赋ID
    /// </summary>
    RoleTalentId = 53,
    /// <summary>
    /// 消耗N个XXid的道具
    /// </summary>
    PropDeduct = 54,
    /// <summary>
    /// 获得N个XXid的道具
    /// </summary>
    PropGainOne = 55,
    /// <summary>
    /// 抽卡N次
    /// </summary>
    DrawCount = 56,
    /// <summary>
    /// 累计获得N个宝物
    /// </summary>
    CardTotal = 57,
    /// <summary>
    /// XXid宝物星级总和达到N
    /// </summary>
    CardStarTotal = 58,
    /// <summary>
    /// XXid的宝物升N星
    /// </summary>
    StarLevelUpOnce = 59,
    /// <summary>
    /// XXid的宝物最高达到N星
    /// </summary>
    StarLevelReach = 60,
    /// <summary>
    /// 宝物精炼N次
    /// </summary>
    CardRefineUpCount = 61,
    /// <summary>
    /// 宝物升星N次
    /// </summary>
    StarUpCount = 62,
    /// <summary>
    /// 累积获得蓝色宝物N个
    /// </summary>
    BlueItemCount = 63,
    /// <summary>
    /// 累积获得紫色宝物N个
    /// </summary>
    PurpleItemCount = 64,
    /// <summary>
    /// 累积获得橙色宝物N个
    /// </summary>
    OrangeItemCount = 65,
    /// <summary>
    /// 累积获得红色宝物N个
    /// </summary>
    RedItemCount = 66,
    /// <summary>
    /// 获得XXid宝物N个
    /// </summary>
    ItemCount = 67,
    /// <summary>
    /// 获得X星宝物N个
    /// </summary>
    StarUpLevelCount = 68,
    /// <summary>
    /// 获得X精炼度宝物N个
    /// </summary>
    CardRefineUpLevelCount = 69,
    /// <summary>
    /// 日常活跃度N点
    /// </summary>
    DailyActivityPoint = 70,
    /// <summary>
    /// 周常活跃度N点
    /// </summary>
    WeeklyActivityPoint = 71,
    /// <summary>
    /// 主线活跃度N点
    /// </summary>
    MainlineActivityPoint = 72,
    /// <summary>
    /// 广告领取体力N次
    /// </summary>
    AdAwardEnergy = 73,
    /// <summary>
    /// 登录N天
    /// </summary>
    LoginDay = 74,
    /// <summary>
    /// 观看广告N次
    /// </summary>
    WatchAdCount = 75,
    /// <summary>
    /// XX任务组内任务完成N个
    /// </summary>
    SubTask = 76,
    /// <summary>
    /// 使用XXid三选一通关X关N波
    /// </summary>
    WavePassByRelic = 77,
    /// <summary>
    /// 组成X羁绊通关X关N波
    /// </summary>
    WavePassByRelicX = 78,
    /// <summary>
    /// 组成X组X羁绊通关X关N次
    /// </summary>
    WavePassByRelicXcount = 79,
    /// <summary>
    /// 不释放逆鳞技通关第X关X波N次
    /// </summary>
    WavePassWithoutSkill = 80,
    /// <summary>
    /// 通关第X关前X波时长不高于N
    /// </summary>
    WavePassBeforeTime = 81,
    /// <summary>
    /// 使用逆鳞技击杀X类型bossN个
    /// </summary>
    KillBossWithSkill = 82,
    /// <summary>
    /// 在X
    /// </summary>
    EventTriggleInChapter = 83,
    /// <summary>
    /// 通过任意主线N次
    /// </summary>
    StageChapterFinishCount = 84,
    /// <summary>
    /// 通过X关X波N次
    /// </summary>
    WavePassCount = 85,
    /// <summary>
    /// 释放逆鳞技通关第X关X波N次
    /// </summary>
    WavePassWithSkill = 86,
    /// <summary>
    /// 通关第X关X波前释放N次逆鳞技
    /// </summary>
    WavePassBeforeWithSkill = 87,
    /// <summary>
    /// 当前拥有XXid的道具N个
    /// </summary>
    PropOwnNow = 88,
    /// <summary>
    /// 商店购买XXid的道具N个
    /// </summary>
    PropGainByExchange = 89,
    /// <summary>
    /// 商店购买XXid的道具N次
    /// </summary>
    PropGainByExchangeTimes = 90,
    /// <summary>
    /// 完成XXid的新手引导
    /// </summary>
    GuideDone = 91,
    /// <summary>
    /// 挑战成功XX类日常本N次
    /// </summary>
    DungeonTypeWinCount = 92,
    /// <summary>
    /// 使用XXid元素龙通过X关N次
    /// </summary>
    WaveFinishElementDragonCount = 93,
    /// <summary>
    /// 使用XXid元素龙挑战X关N次
    /// </summary>
    BattleElementDragonCount = 94,
    /// <summary>
    /// X关击杀X类型bossN次
    /// </summary>
    ChapterKillBossKindCount = 95,
    /// <summary>
    /// 通关X关N次
    /// </summary>
    ChapterPassCount = 96,
    /// <summary>
    /// 在X关释放N次逆鳞技
    /// </summary>
    ChapterBattleWithSkillCount = 97,
    /// <summary>
    /// 激活XXid的宝物N次
    /// </summary>
    CardActiveTimes = 98,
    /// <summary>
    /// 升级XXid的熟练度N次
    /// </summary>
    RegionExpLevelUpCountById = 99,
    /// <summary>
    /// X类型的首充后登录N天
    /// </summary>
    FirstRechargeLogin = 100,
    /// <summary>
    /// XXid充值N次
    /// </summary>
    Recharge = 101,
    /// <summary>
    /// 注册N天
    /// </summary>
    RegisterDay = 102,
    /// <summary>
    /// X卡池抽卡N次
    /// </summary>
    DrawCountByPool = 103,
    /// <summary>
    /// 装备分解N次
    /// </summary>
    EquipmentDecompose = 104,
    /// <summary>
    /// 任意充值N分
    /// </summary>
    RechargeAmountTotal = 105,
    /// <summary>
    /// XX模块任务活跃度达到N
    /// </summary>
    TaskLivenessByModule = 106,
    /// <summary>
    /// 拥有N个好友
    /// </summary>
    SocialFriendsAmount = 107,
    /// <summary>
    /// 赠送N次友情点
    /// </summary>
    SocialGiftSendTimes = 108,
    /// <summary>
    /// 发出N次好友申请
    /// </summary>
    SocialApplyTimes = 109,
    /// <summary>
    /// XXid宝物收集度达到N
    /// </summary>
    CardCollectionById = 110,
    /// <summary>
    /// XX阵营宝物收集度达到N
    /// </summary>
    CardCollectionByCamp = 111,
    /// <summary>
    /// 宝物总收集度达到N
    /// </summary>
    CardCollectionTotal = 112,
    /// <summary>
    /// 总释放N次逆鳞技
    /// </summary>
    TotalBattleWithSkillCount = 113,
    /// <summary>
    /// 总组成N次X羁绊
    /// </summary>
    TotalRelicXcount = 114,
    /// <summary>
    /// 同时拥有X个及以上的X羁绊N次
    /// </summary>
    RelicXcount = 115,
    /// <summary>
    /// 组成N次X属性的羁绊
    /// </summary>
    RelicXcountByElement = 116,
    /// <summary>
    /// 使用X属性击杀N个敌人
    /// </summary>
    DefeatCountByElement = 117,
    /// <summary>
    /// 使用X类型伤害击杀N个敌人
    /// </summary>
    DefeatCountBySource = 118,
    /// <summary>
    /// 经历N次X随机事件
    /// </summary>
    RegionEventCountByType = 119,
    /// <summary>
    /// 吞噬子弹N次
    /// </summary>
    AbsorbBulletCount = 120,
    /// <summary>
    /// 整体无伤通过X关N次
    /// </summary>
    ChapterPassCountNoDamage = 121,
    /// <summary>
    /// XXid的广告观看N次
    /// </summary>
    WatchAdCountById = 122,
    /// <summary>
    /// X类型战斗无伤通关N次
    /// </summary>
    ChapterPassCountNoDamageByType = 123,
    /// <summary>
    /// 组成N次X伤害属性的羁绊
    /// </summary>
    RelicXcountByDmgSource = 124,
    /// <summary>
    /// 可激活且未激活N条元素龙
    /// </summary>
    DragonActivatable = 125,
    /// <summary>
    /// 使用终结技击杀所有类型bossN个
    /// </summary>
    KillBossAllWithSkill = 126,
    /// <summary>
    /// 通过X大类副本的所有子副本的X层
    /// </summary>
    DungeonPassLayers = 127,
    /// <summary>
    /// 获得N件X品质随机属性的装备
    /// </summary>
    EquipGainRandomAttrByTier = 128,
    /// <summary>
    /// 激活Xid的装备套装的X件套效果
    /// </summary>
    EquipActiveSuit = 129,
    /// <summary>
    /// 挑战XX子类日常本N次
    /// </summary>
    DungeonSubTypeCount = 130,
    /// <summary>
    /// 挑战成功XX子类日常本N次
    /// </summary>
    DungeonSubTypeWinCount = 131,
    /// <summary>
    /// XXid任务完成
    /// </summary>
    TaskDone = 132,
    /// <summary>
    /// XXid的活动获得活跃度N点
    /// </summary>
    ActivityPointById = 133,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmConditionParamterTypeMax = 134,
  }

  public enum CSEnmEquipPart {
    /// <summary>
    /// 装备部位
    /// </summary>
    EquipPartNone = 0,
    /// <summary>
    /// 武器
    /// </summary>
    Weapon = 1,
    /// <summary>
    /// 头盔
    /// </summary>
    Helmet = 2,
    /// <summary>
    /// 上衣
    /// </summary>
    Armor = 3,
    /// <summary>
    /// 护腕
    /// </summary>
    Glove = 4,
    /// <summary>
    /// 裤子
    /// </summary>
    Pants = 5,
    /// <summary>
    /// 鞋子
    /// </summary>
    Shoe = 6,
    /// <summary>
    /// 饰品
    /// </summary>
    Ornament = 7,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmEquipPartMax = 8,
  }

  public enum CSEnmQualityType {
    /// <summary>
    /// 品质
    /// </summary>
    QualityTypeNone = 0,
    /// <summary>
    /// 绿色
    /// </summary>
    Green = 1,
    /// <summary>
    /// 蓝色
    /// </summary>
    Blue = 2,
    /// <summary>
    /// 紫色
    /// </summary>
    Purple = 3,
    /// <summary>
    /// 橙色
    /// </summary>
    Orange = 4,
    /// <summary>
    /// 红色
    /// </summary>
    Red = 5,
    /// <summary>
    /// 银色
    /// </summary>
    Silver = 6,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmQualityTypeMax = 7,
  }

  public enum CSEnmPropertyEffect {
    /// <summary>
    /// 属性类型
    /// </summary>
    PropertyEffectNone = 0,
    /// <summary>
    /// 固定值
    /// </summary>
    FixedValue = 1,
    /// <summary>
    /// 单一装备
    /// </summary>
    SingleEquipment = 2,
    /// <summary>
    /// 所有装备
    /// </summary>
    AllEquipment = 3,
    /// <summary>
    /// 角色效果
    /// </summary>
    RoleEffect = 4,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmPropertyEffectMax = 5,
  }

  public enum CSEnmPropType {
    /// <summary>
    /// 道具类型
    /// </summary>
    PropTypeNone = 0,
    /// <summary>
    /// 货币
    /// </summary>
    Currency = 9,
    /// <summary>
    /// 道具
    /// </summary>
    Item = 1,
    /// <summary>
    /// 卡牌
    /// </summary>
    Card = 2,
    /// <summary>
    /// 装扮
    /// </summary>
    Dress = 3,
    /// <summary>
    /// 装备
    /// </summary>
    Equip = 4,
    /// <summary>
    /// 宝箱
    /// </summary>
    Chest = 5,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmPropTypeMax = 10,
  }

  public enum CSEnmPropSubType {
    /// <summary>
    /// 道具类型
    /// </summary>
    PropSubTypeNone = 0,
    /// <summary>
    /// 钻石
    /// </summary>
    PayDiamond = 1,
    /// <summary>
    /// 钻石
    /// </summary>
    Diamond = 2,
    /// <summary>
    /// 金币
    /// </summary>
    Coin = 3,
    /// <summary>
    /// 体力
    /// </summary>
    Energy = 4,
    /// <summary>
    /// 经验
    /// </summary>
    Exp = 5,
    /// <summary>
    /// 封印石
    /// </summary>
    RegionPoint = 6,
    /// <summary>
    /// 主线成就点
    /// </summary>
    MainLinePonit = 7,
    /// <summary>
    /// 周常活跃度
    /// </summary>
    WeeklyPoint = 8,
    /// <summary>
    /// 日常活跃度
    /// </summary>
    DailyPoint = 9,
    /// <summary>
    /// 天赋点
    /// </summary>
    TalentPoint = 10,
    /// <summary>
    /// 卡牌碎片
    /// </summary>
    CardDebris = 11,
    /// <summary>
    /// 技能碎片
    /// </summary>
    SkillDebris = 12,
    /// <summary>
    /// 完整卡牌
    /// </summary>
    CardNormal = 13,
    /// <summary>
    /// 完整技能
    /// </summary>
    SkillNormal = 14,
    /// <summary>
    /// 通用卡牌碎片
    /// </summary>
    CommonCardDebris = 15,
    /// <summary>
    /// 冒险商店货币
    /// </summary>
    RegionCurrency = 16,
    /// <summary>
    /// 预览类型
    /// </summary>
    ItemPreview = 17,
    /// <summary>
    /// 主线体力
    /// </summary>
    StageEnergy = 18,
    /// <summary>
    /// 章节解锁
    /// </summary>
    StageUnlock = 19,
    /// <summary>
    /// 元素龙残片
    /// </summary>
    ElementRelic = 20,
    /// <summary>
    /// 技能残片
    /// </summary>
    UltimateSkillRelic = 21,
    /// <summary>
    /// 代金币
    /// </summary>
    PropSubTypeVoucher = 22,
    /// <summary>
    /// 友情点
    /// </summary>
    FriendPoint = 23,
    /// <summary>
    /// 广告券
    /// </summary>
    AdTicket = 24,
    /// <summary>
    /// 复活币
    /// </summary>
    RebornCoin = 25,
    /// <summary>
    /// 头像
    /// </summary>
    Head = 26,
    /// <summary>
    /// 头像框
    /// </summary>
    Frame = 27,
    /// <summary>
    /// 高额机会券
    /// </summary>
    ExtraTicket = 28,
    /// <summary>
    /// 双倍挑战券
    /// </summary>
    DoubleTicket = 29,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmPropSubTypeMax = 30,
  }

  public enum CSEnmBagTabType {
    /// <summary>
    /// 背包页签类型
    /// </summary>
    NoneTab = 0,
    /// <summary>
    /// 道具
    /// </summary>
    PropTab = 1,
    /// <summary>
    /// 装备
    /// </summary>
    EquipTab = 2,
    /// <summary>
    /// 宝箱
    /// </summary>
    ChestTab = 3,
    /// <summary>
    /// 所有
    /// </summary>
    AllTab = 4,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmBagTabTypeMax = 5,
  }

  public enum CSEnmEquipmentLevelType {
    /// <summary>
    /// 装备等级类型
    /// </summary>
    EquipmentLevelTypeNone = 0,
    /// <summary>
    /// 普通升级
    /// </summary>
    TypeNormal = 1,
    /// <summary>
    /// 精炼升级
    /// </summary>
    TypeRefine = 2,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmEquipmentLevelTypeMax = 3,
  }

  public enum CSEnmRegionEventType {
    /// <summary>
    /// 事件类型
    /// </summary>
    EventTypeNone = 0,
    /// <summary>
    /// 恶魔
    /// </summary>
    Evil = 1,
    /// <summary>
    /// 转盘
    /// </summary>
    Roll = 2,
    /// <summary>
    /// 天使
    /// </summary>
    Angel = 3,
    /// <summary>
    /// 精英
    /// </summary>
    Elite = 4,
    /// <summary>
    /// 金币
    /// </summary>
    Coins = 5,
    /// <summary>
    /// Max
    /// </summary>
    EventMax = 6,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmRegionEventTypeMax = 7,
  }

  public enum CSEnmAdType {
    /// <summary>
    /// 广告类型
    /// </summary>
    AdTypeNone = 0,
    /// <summary>
    /// 死亡复活
    /// </summary>
    AdReborn = 1,
    /// <summary>
    /// 刷新三选一
    /// </summary>
    AdRelic = 2,
    /// <summary>
    /// 副本体力领取
    /// </summary>
    AdEnergy = 3,
    /// <summary>
    /// 快速挂机
    /// </summary>
    AdHangup = 4,
    /// <summary>
    /// 免费单抽
    /// </summary>
    AdDraw = 5,
    /// <summary>
    /// 广告礼包
    /// </summary>
    AdGift = 6,
    /// <summary>
    /// 局内转盘
    /// </summary>
    AdRoll = 7,
    /// <summary>
    /// 购买金币
    /// </summary>
    AdBuyCoin = 8,
    /// <summary>
    /// 奖励领取
    /// </summary>
    AdAwards = 9,
    /// <summary>
    /// 商店礼包
    /// </summary>
    AdRecharge = 10,
    /// <summary>
    /// 主线体力领取
    /// </summary>
    AdStageEnergy = 11,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmAdTypeMax = 12,
  }

  public enum CSEnmSysType {
    /// <summary>
    /// 系统类型
    /// </summary>
    SysTypeNone = 0,
    /// <summary>
    /// 主界面
    /// </summary>
    SysMain = 1,
    /// <summary>
    /// 广告系统
    /// </summary>
    SysAd = 2,
    /// <summary>
    /// 背包系统
    /// </summary>
    SysBag = 3,
    /// <summary>
    /// 战斗系统
    /// </summary>
    SysBattle = 4,
    /// <summary>
    /// 卡牌系统
    /// </summary>
    SysCard = 5,
    /// <summary>
    /// 装备系统
    /// </summary>
    SysEquipment = 6,
    /// <summary>
    /// 挂机系统
    /// </summary>
    SysHangup = 7,
    /// <summary>
    /// 道具系统
    /// </summary>
    SysItem = 8,
    /// <summary>
    /// 邮件系统
    /// </summary>
    SysMail = 9,
    /// <summary>
    /// 熟练度系统
    /// </summary>
    SysRegion = 10,
    /// <summary>
    /// 角色系统
    /// </summary>
    SysRole = 11,
    /// <summary>
    /// 大招系统
    /// </summary>
    SysSkill = 12,
    /// <summary>
    /// 元素龙系统
    /// </summary>
    SysSkin = 13,
    /// <summary>
    /// 天赋系统
    /// </summary>
    SysTalent = 14,
    /// <summary>
    /// 任务系统
    /// </summary>
    SysTask = 15,
    /// <summary>
    /// 角色升级
    /// </summary>
    SysRoleLevelUp = 16,
    /// <summary>
    /// 战斗主线
    /// </summary>
    SysStage = 17,
    /// <summary>
    /// 战斗远征
    /// </summary>
    SysExpedition = 18,
    /// <summary>
    /// 战斗元素龙
    /// </summary>
    SysDragonStory = 19,
    /// <summary>
    /// 战斗副本
    /// </summary>
    SysDungeon = 20,
    /// <summary>
    /// 卡牌抽卡
    /// </summary>
    SysCardDraw = 21,
    /// <summary>
    /// 卡牌精炼
    /// </summary>
    SysCardRefine = 22,
    /// <summary>
    /// 卡牌升星
    /// </summary>
    SysCardStar = 23,
    /// <summary>
    /// 卡牌共鸣
    /// </summary>
    SysCardResonance = 24,
    /// <summary>
    /// 装备精炼
    /// </summary>
    SysEquipRefine = 25,
    /// <summary>
    /// 装备升级
    /// </summary>
    SysEquipLevel = 26,
    /// <summary>
    /// 装备分解
    /// </summary>
    SysEquipDecompose = 27,
    /// <summary>
    /// 任务日常
    /// </summary>
    SysTaskMainline = 28,
    /// <summary>
    /// 任务周常
    /// </summary>
    SysTaskWeekly = 29,
    /// <summary>
    /// 任务主线
    /// </summary>
    SysTaskDaily = 30,
    /// <summary>
    /// 熟练度
    /// </summary>
    SysRegionAchieve = 31,
    /// <summary>
    /// 熟练度
    /// </summary>
    SysRegionShop = 32,
    /// <summary>
    /// GM指令
    /// </summary>
    SysGm = 33,
    /// <summary>
    /// 玩家系统全开放
    /// </summary>
    SysRoleOpen = 34,
    /// <summary>
    /// 签到
    /// </summary>
    SysSign = 35,
    /// <summary>
    /// 好友
    /// </summary>
    SysSocial = 36,
    /// <summary>
    /// 商店
    /// </summary>
    SysShop = 37,
    /// <summary>
    /// 商城
    /// </summary>
    SysRecharge = 38,
    /// <summary>
    /// 排行榜
    /// </summary>
    SysRank = 39,
    /// <summary>
    /// 新手任务
    /// </summary>
    SysNoviciatetTask = 40,
    /// <summary>
    /// 体力福利任务
    /// </summary>
    SysEnergyTask = 41,
    /// <summary>
    /// 聊天
    /// </summary>
    SysChat = 42,
    /// <summary>
    /// 元素龙升级
    /// </summary>
    SysDragonLevelUp = 43,
    /// <summary>
    /// 宝物收集
    /// </summary>
    SysCardPoint = 44,
    /// <summary>
    /// Max
    /// </summary>
    SysMax = 45,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmSysTypeMax = 46,
  }

  public enum CSEnmElementType {
    /// <summary>
    /// 元素类型
    /// </summary>
    ElementTypeNone = 0,
    /// <summary>
    /// 火
    /// </summary>
    Fire = 1,
    /// <summary>
    /// 风
    /// </summary>
    Wind = 2,
    /// <summary>
    /// 电
    /// </summary>
    Electric = 3,
    /// <summary>
    /// 毒
    /// </summary>
    Poison = 4,
    /// <summary>
    /// 冰
    /// </summary>
    Ice = 5,
    /// <summary>
    /// 所有
    /// </summary>
    All = 100,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmElementTypeMax = 101,
  }

  public enum CSEnmDungeonType {
    /// <summary>
    /// 副本类型
    /// </summary>
    DungeonTypeNone = 0,
    /// <summary>
    /// 装备本
    /// </summary>
    DungeonEquipment = 1,
    /// <summary>
    /// 碎片本
    /// </summary>
    DungeonDebris = 2,
    /// <summary>
    /// 天副本
    /// </summary>
    DungeonTalent = 3,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmDungeonTypeMax = 4,
  }

  public enum CSEnmProduceEffectType {
    /// <summary>
    /// 生产效果加成模块
    /// </summary>
    ProduceEffectTypeNone = 0,
    /// <summary>
    /// 主线结算
    /// </summary>
    TypeStage = 1,
    /// <summary>
    /// 挂机结算
    /// </summary>
    TypeHangUp = 2,
    /// <summary>
    /// 局内随机时间
    /// </summary>
    TypeRegionEvent = 3,
    /// <summary>
    /// 远征结算
    /// </summary>
    TypeExpedition = 4,
    /// <summary>
    /// 熟练度三选一刷新
    /// </summary>
    TypeRelicRefresh = 5,
    /// <summary>
    /// 物品商店兑换次数
    /// </summary>
    TypeItemShop = 6,
    /// <summary>
    /// 日常本战斗高额奖励次数
    /// </summary>
    TypeDungeonSpecAwardsTimes = 7,
    /// <summary>
    /// 远征战斗次数
    /// </summary>
    TypeExpeditionTimes = 8,
    /// <summary>
    /// 日常本战斗次数
    /// </summary>
    TypeDungeonTimes = 9,
    /// <summary>
    /// 主线体力翻倍次数
    /// </summary>
    TypStageBonusTimes = 10,
    /// <summary>
    /// 日常本体力翻倍次数
    /// </summary>
    TypDungeonBonusTimes = 11,
    /// <summary>
    /// 战斗复活次数
    /// </summary>
    TypeReviveTimes = 12,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmProduceEffectTypeMax = 13,
  }

  public enum CSEnmProduceEffectSubType {
    /// <summary>
    /// 生产效果加成道具类型
    /// </summary>
    ProduceEffectSubTypeNone = 0,
    /// <summary>
    /// 金币
    /// </summary>
    SubTypeCoin = 1,
    /// <summary>
    /// 挂机时长上限
    /// </summary>
    SubTypeTimeLimit = 2,
    /// <summary>
    /// 经验
    /// </summary>
    SubTypeExp = 3,
    /// <summary>
    /// 经验与金币
    /// </summary>
    SubTypeExpCoin = 4,
    /// <summary>
    /// 熟练度
    /// </summary>
    SubTypeProficiency = 5,
    /// <summary>
    /// 卡牌碎片
    /// </summary>
    SubTypeDebris = 6,
    /// <summary>
    /// 随机事件恶魔
    /// </summary>
    RegionEventEvil = 7,
    /// <summary>
    /// 随机事件转盘
    /// </summary>
    RegionEventRoll = 8,
    /// <summary>
    /// 随机事件天使
    /// </summary>
    RegionEventAngel = 9,
    /// <summary>
    /// 随机事件精英
    /// </summary>
    RegionEventElite = 10,
    /// <summary>
    /// 随机事件金币
    /// </summary>
    RegionEventCoins = 11,
    /// <summary>
    /// 每日
    /// </summary>
    SubTypeDaily = 12,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmProduceEffectSubTypeMax = 13,
  }

  public enum CSEnmEnemyType {
    /// <summary>
    /// 普通波次
    /// </summary>
    EnemyNormal = 0,
    /// <summary>
    /// Boss波次
    /// </summary>
    EnemyBoss = 1,
    /// <summary>
    /// 占位类型
    /// </summary>
    EnemyEmpty = 2,
    /// <summary>
    /// 教学波次
    /// </summary>
    EnemyTutorial = 3,
    /// <summary>
    /// 金币波次
    /// </summary>
    EnemyCoin = 4,
    /// <summary>
    /// 精英波次
    /// </summary>
    EnemyElite = 5,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmEnemyTypeMax = 6,
  }

  public enum CSEnmTaskModule {
    /// <summary>
    /// 任务所属类型
    /// </summary>
    TaskModuleNone = 0,
    /// <summary>
    /// 日常
    /// </summary>
    DailyTask = 1,
    /// <summary>
    /// 周常
    /// </summary>
    WeeklyTask = 2,
    /// <summary>
    /// 主线
    /// </summary>
    MainlineTask = 3,
    /// <summary>
    /// 祈愿
    /// </summary>
    WishTask = 4,
    /// <summary>
    /// 签到
    /// </summary>
    SignTask = 5,
    /// <summary>
    /// 首充奖励
    /// </summary>
    FirstRewardTask = 6,
    /// <summary>
    /// 新手8日
    /// </summary>
    RookieTask = 7,
    /// <summary>
    /// 体力福利任务
    /// </summary>
    EnergyTask = 8,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmTaskModuleMax = 9,
  }

  public enum CSEnmInsertBtType {
    /// <summary>
    /// 序章专用
    /// </summary>
    NotInsert = 0,
    /// <summary>
    /// 波次开始时
    /// </summary>
    BeforeWave = 1,
    /// <summary>
    /// Boss入场后
    /// </summary>
    BossAfterStart = 2,
    /// <summary>
    /// Boss死亡前
    /// </summary>
    BossBeforeEnd = 3,
    /// <summary>
    /// 波次结束后
    /// </summary>
    AfterWave = 4,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmInsertBtTypeMax = 5,
  }

  public enum CSEnmStatPeriodType {
    /// <summary>
    /// 统计周期
    /// </summary>
    StatPeriodNone = 0,
    /// <summary>
    /// 永久统计
    /// </summary>
    StatPeriodForever = 1,
    /// <summary>
    /// 每日统计
    /// </summary>
    StatPeriodDaily = 2,
    /// <summary>
    /// 每周统计
    /// </summary>
    StatPeriodWeekly = 3,
    /// <summary>
    /// 每月统计
    /// </summary>
    StatPeriodMonthly = 4,
    /// <summary>
    /// Max
    /// </summary>
    StatPeriodMax = 5,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmStatPeriodTypeMax = 6,
  }

  public enum CSEnmRechargeType {
    /// <summary>
    /// 默认
    /// </summary>
    RechargeTypeDefault = 0,
    /// <summary>
    /// 礼包
    /// </summary>
    RechargeTypeGift = 1,
    /// <summary>
    /// 月卡
    /// </summary>
    RechargeTypeMonthCard = 2,
    /// <summary>
    /// 推送礼包
    /// </summary>
    RechargeTypePushGift = 3,
    /// <summary>
    /// Max
    /// </summary>
    RechargeTypeMax = 4,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmRechargeTypeMax = 5,
  }

  public enum CSEnmExchangeShopType {
    /// <summary>
    /// 付费商店类型
    /// </summary>
    ExchangeShopTypeNone = 0,
    /// <summary>
    /// 普通商店
    /// </summary>
    ExchangeShopTypeNormal = 1,
    /// <summary>
    /// Max
    /// </summary>
    ExchangeShopTypeMax = 2,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmExchangeShopTypeMax = 3,
  }

  public enum CSEnmSystemMailType {
    /// <summary>
    /// 系统邮件类型
    /// </summary>
    SystemMailTypeNone = 0,
    /// <summary>
    /// 背包溢出邮件
    /// </summary>
    SystemMailTypeBag = 1,
    /// <summary>
    /// Max
    /// </summary>
    SystemMailTypeMax = 2,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmSystemMailTypeMax = 3,
  }

  public enum CSEnmCardCampType {
    /// <summary>
    /// 宝物阵营枚举
    /// </summary>
    CardCampTypeNone = 0,
    /// <summary>
    /// 知识
    /// </summary>
    CardCampKnowledge = 1,
    /// <summary>
    /// 意志
    /// </summary>
    CardCampWill = 2,
    /// <summary>
    /// 力量
    /// </summary>
    CardCampStrength = 3,
    /// <summary>
    /// 财富
    /// </summary>
    CardCampWealth = 4,
    /// <summary>
    /// 宝物种类数量
    /// </summary>
    MaxTypeCount = 5,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmCardCampTypeMax = 6,
  }

  public enum CSEnmGlobalConfig {
    /// <summary>
    /// ccc
    /// </summary>
    GlobalNone = 0,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalMainLinePonit = 1,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalWeeklyPoint = 2,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalDailyPoint = 3,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalDiamond = 4,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalCoin = 5,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalEnergy = 6,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalExp = 7,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalTalentPoint = 8,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalElementDragonChapterRoleLv = 9,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalDiamondBuyCoinShopId1 = 10,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalDiamondBuyCoinShopId2 = 11,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalShopTicket = 12,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalDiamondBuyEnergyShopId = 13,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalStageEnergy = 14,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalDiamondBuyStageEnergyShopId = 15,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalDrawCardConditionId = 16,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalHangUpAwardsShowTime = 17,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalLoginDayCountId = 18,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalBuyRollShopId = 19,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalEquipmentDecomposeRedPoint = 20,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalPromoteRercentSurpassValue = 21,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalMoneyVoucher = 22,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalBuyDiamondShopId = 23,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalPayDiamond = 24,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalFriendShopHyperLinkIndex = 25,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalMainLineShopStopRefreshTime = 26,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalExpeditionDailyCountIndex = 27,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalRegisterDayCountId = 28,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalNoviciatetTaskCountId = 29,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalNoviciatetTaskPoint = 30,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalAdTicketId = 31,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalReviveCoinId = 32,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalReviveHardCodeIndex = 33,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalFriendLimitHardCode = 34,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalFriendGiftHardCode = 35,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalNormalCostBonusLimitHardCode = 36,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalDungeonCostBonusLimitHardCode = 37,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalRankTypeHardCode = 38,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalStageEnergyPropId = 39,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalDailyEnergyPropId = 40,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalRenameHardCode = 41,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalNormalCostBonusCurrencyBuyShopId = 42,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalNormalCostBonusPropUseShopId = 43,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalDungeonCostBonusCurrencyBuyShopId = 44,
    /// <summary>
    /// ccc
    /// </summary>
    GlobalDungeonCostBonusPropUseShopId = 45,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmGlobalConfigMax = 46,
  }

  public enum CSEnmRankType {
    /// <summary>
    /// 排行榜枚举
    /// </summary>
    RankTypeNone = 0,
    /// <summary>
    /// 主线
    /// </summary>
    RankTypeStage = 1,
    /// <summary>
    /// 远征
    /// </summary>
    RankTypeExpedition = 2,
    /// <summary>
    /// 装备
    /// </summary>
    RankTypeWeapon = 3,
    /// <summary>
    /// 防具
    /// </summary>
    RankTypeArmor = 4,
    /// <summary>
    /// 战力
    /// </summary>
    RankTypePower = 5,
    /// <summary>
    /// 宝物收集
    /// </summary>
    RankTypeCardCollect = 6,
    /// <summary>
    /// 意志类宝物收集
    /// </summary>
    RankTypeVolitionCardCollect = 7,
    /// <summary>
    /// 智慧类宝物收集
    /// </summary>
    RankTypeWisdomCardCollect = 8,
    /// <summary>
    /// 力量类宝物收集
    /// </summary>
    RankTypePowerCardCollect = 9,
    /// <summary>
    /// 财富类宝物收集
    /// </summary>
    RankTypeWealthCardCollect = 10,
    /// <summary>
    /// Max
    /// </summary>
    RankTypeMax = 11,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmRankTypeMax = 12,
  }

  public enum CSEnmBroadcastType {
    /// <summary>
    /// 广播类型
    /// </summary>
    BroadcastTypeNone = 0,
    /// <summary>
    /// 获得N品质宝物
    /// </summary>
    BroadcastTypeCardQuality = 1,
    /// <summary>
    /// 宝物N星
    /// </summary>
    BroadcastTypeCardStar = 2,
    /// <summary>
    /// 宝物N精炼等级
    /// </summary>
    BroadcastTypeCardRefineLevel = 3,
    /// <summary>
    /// 解锁主线章节N关
    /// </summary>
    BroadcastTypeChapterStage = 4,
    /// <summary>
    /// 角色N阶
    /// </summary>
    BroadcastTypeRoleEvoLevel = 5,
    /// <summary>
    /// 激活龙的全部传承点
    /// </summary>
    BroadcastTypeDragonTalentActiveAll = 6,
    /// <summary>
    /// 激活终结技
    /// </summary>
    BroadcastTypeSkillActive = 7,
    /// <summary>
    /// 终结技N星
    /// </summary>
    BroadcastTypeSkillStar = 8,
    /// <summary>
    /// 激活元素龙
    /// </summary>
    BroadcastTypeDragonActive = 9,
    /// <summary>
    /// 元素龙N星
    /// </summary>
    BroadcastTypeDragonStar = 10,
    /// <summary>
    /// N1个装备N2级
    /// </summary>
    BroadcastTypeEquipLevel = 11,
    /// <summary>
    /// N1个装备N2精炼等级
    /// </summary>
    BroadcastTypeEquipRefineLevel = 12,
    /// <summary>
    /// N1id的装备属性达到N2数值
    /// </summary>
    BroadcastTypeEquipAttrValue = 13,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmBroadcastTypeMax = 14,
  }

  public enum CSEnmInGameBoostType {
    /// <summary>
    /// ccc
    /// </summary>
    InGameBoostTypeNone = 0,
    /// <summary>
    /// ccc
    /// </summary>
    ElementWeightChange = 1,
    /// <summary>
    /// ccc
    /// </summary>
    CategoryWeightChange = 2,
    /// <summary>
    /// ccc
    /// </summary>
    ElementQualityUpgrade = 3,
    /// <summary>
    /// ccc
    /// </summary>
    CategoryQualityUpgrade = 4,
    /// <summary>
    /// ccc
    /// </summary>
    ItemBuffCount = 5,
    /// <summary>
    /// ccc
    /// </summary>
    PlayerDirectStats = 6,
    /// <summary>
    /// ccc
    /// </summary>
    ReplaceRelic = 7,
    /// <summary>
    /// ccc
    /// </summary>
    ElementQualityBoost = 8,
    /// <summary>
    /// ccc
    /// </summary>
    CategoryQualityBoost = 9,
    /// <summary>
    /// ccc
    /// </summary>
    AddBuff = 10,
    /// <summary>
    /// ccc
    /// </summary>
    RelicQualityBoost = 11,
    /// <summary>
    /// ccc
    /// </summary>
    RelicQualityUpgrade = 12,
    /// <summary>
    /// ccc
    /// </summary>
    PlayerStatsPermilAdd = 13,
    /// <summary>
    /// ccc
    /// </summary>
    InitialRelics = 14,
    /// <summary>
    /// ccc
    /// </summary>
    MetaFunc = 15,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmInGameBoostTypeMax = 16,
  }

  public enum CSEnmActivityType {
    /// <summary>
    /// 活动类型
    /// </summary>
    ActivityTypeNone = 0,
    /// <summary>
    /// BattlePass
    /// </summary>
    ActivityTypeBp = 1,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmActivityTypeMax = 2,
  }

  public enum CSEnmActivitySubType {
    /// <summary>
    /// 活动子类型
    /// </summary>
    ActivitySubTypeNone = 0,
    /// <summary>
    /// Max
    /// </summary>
    KCsenmActivitySubTypeMax = 1,
  }

  #endregion

}

#endregion Designer generated code
