// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cserror.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::ILRuntime.Protobuf;
using pbc = global::ILRuntime.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Csp {

  #region Enums
  /// <summary>
  ///========== enum define ==========
  /// </summary>
  public enum CSErrorCode {
    /// <summary>
    /// 无错误
    /// </summary>
    KCserrorNone = 0,
    /// <summary>
    /// 系统错误
    /// </summary>
    KCserrorSystem = 1,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemNotEnoughGold = 2,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemNotEnoughDiamond = 3,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemLevelNotEnough = 5,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemNotEnoughPower = 8,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemBagExtendLimit = 9,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemCdlimit = 11,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemBagIsFull = 21,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemPropBagFull = 22,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemEquipBagFull = 23,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemSendMailPropBagFull = 26,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemSendMailEquipBagFull = 27,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemReceiveMailBagFull = 28,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemReceiveMailEquipFull = 29,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemItemNotEnough = 31,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemItemExpired = 32,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemRoleNameInvalid = 33,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemLocked = 34,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorConditionLocked = 40,
    /// <summary>
    /// 卡牌模块
    /// </summary>
    KCserrorCardLack = 51,
    /// <summary>
    /// 卡牌模块
    /// </summary>
    KCserrorCardLocked = 52,
    /// <summary>
    /// 卡牌模块
    /// </summary>
    KCserrorCardUnlocked = 53,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemRoleNameLength = 61,
    /// <summary>
    /// 系统模块
    /// </summary>
    KCserrorSystemRoleNameIllegal = 62,
    /// <summary>
    /// 聊天模块
    /// </summary>
    KCserrorSystemChatTextLength = 80,
    /// <summary>
    /// 聊天模块
    /// </summary>
    KCserrorSystemChatTextIllegal = 81,
    /// <summary>
    /// 聊天模块
    /// </summary>
    KCserrorSystemChatCdlimit = 85,
    /// <summary>
    /// 聊天模块
    /// </summary>
    KCserrorSystemChatSpeakBanned = 86,
    /// <summary>
    /// 聊天模块
    /// </summary>
    KCserrorSystemChatWithSelf = 87,
    /// <summary>
    /// 统计模块
    /// </summary>
    KCserrorStatDailyLimit = 90,
    /// <summary>
    /// 统计模块
    /// </summary>
    KCserrorStatWeeklyLimit = 91,
    /// <summary>
    /// 统计模块
    /// </summary>
    KCserrorStatMonthlyLimit = 92,
    /// <summary>
    /// 统计模块
    /// </summary>
    KCserrorStatForeverLimit = 93,
    /// <summary>
    /// 礼包码错误
    /// </summary>
    KCserrorSystemGiftcodeInvalid = 100,
    /// <summary>
    /// 礼包码次数不足
    /// </summary>
    KCserrorSystemGiftcodeSellout = 101,
    /// <summary>
    /// 礼包码过期
    /// </summary>
    KCserrorSystemGiftcodeExpired = 102,
    /// <summary>
    /// 排行榜缓存未初始化
    /// </summary>
    KCserrorSystemRankNull = 103,
    /// <summary>
    /// 非合理广告
    /// </summary>
    KCserrorAdInvalid = 150,
    /// <summary>
    /// 广告超周期观看限制
    /// </summary>
    KCserrorAdLimit = 151,
    /// <summary>
    /// 广告还在CD期内
    /// </summary>
    KCserrorAdInCd = 152,
    /// <summary>
    /// 展示幻化列表过长
    /// </summary>
    KCserrorDressDragonTooMany = 201,
    /// <summary>
    /// 展示幻化ID不存在
    /// </summary>
    KCserrorDressDragonInvalid = 202,
    /// <summary>
    /// 商店模块
    /// </summary>
    KCserrorShopSystemBuyLimit = 401,
    /// <summary>
    /// 道具模块
    /// </summary>
    KCserrorItemSystem = 500,
    /// <summary>
    /// 天赋模块
    /// </summary>
    KCserrorTalentNotEnough = 551,
    /// <summary>
    /// 装备模块
    /// </summary>
    KCserrorEquipmentTooMany = 600,
    /// <summary>
    /// Pve模块
    /// </summary>
    KCserrorPveDayBattleCountLimit = 1804,
    /// <summary>
    /// Pve模块
    /// </summary>
    KCserrorPveBattleReenterDeny = 1805,
    /// <summary>
    /// 新手引导已完成
    /// </summary>
    KCserrorGuideDone = 3001,
    /// <summary>
    /// 新手引导传参错误
    /// </summary>
    KCserrorGuideParams = 3002,
    /// <summary>
    /// 主线进度已完成
    /// </summary>
    KCserrorStoryDone = 3011,
    /// <summary>
    /// 主线进度传参错误
    /// </summary>
    KCserrorStoryParams = 3012,
    /// <summary>
    /// 章节ID错误
    /// </summary>
    KCserrorBattleCommonInvalidChapterId = 5200,
    /// <summary>
    /// 没有剩余的可玩章节了
    /// </summary>
    KCserrorBattleCommonNoLeftChapter = 5201,
    /// <summary>
    /// 战斗未解锁
    /// </summary>
    KCserrorBattleNotUnlock = 5202,
    /// <summary>
    /// 战斗已解锁
    /// </summary>
    KCserrorBattleUnlocked = 5203,
    /// <summary>
    /// 战斗超时
    /// </summary>
    KCserrorBattleTimeout = 5204,
    /// <summary>
    /// 远征试炼
    /// </summary>
    KCserrorExpenditionTrialNoTickets = 5300,
    /// <summary>
    /// 功能未解锁
    /// </summary>
    KCserrorNotUnlock = 5350,
    /// <summary>
    /// 道具使用次数已用完
    /// </summary>
    KCserrorNoEnoughTickets = 5353,
    /// <summary>
    /// 活动系统
    /// </summary>
    KCserrorActivityNotOpen = 6001,
    /// <summary>
    /// token校验不通过
    /// </summary>
    KCserrorTokenInvalid = 8000,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialOpSelf = 9001,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialFriendListFull = 9011,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialTargetFriendListFull = 9012,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialIsFriend = 9013,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialNotFriend = 9014,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialApplyListFull = 9021,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialTargetApplyListFull = 9022,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialInApplyList = 9023,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialNotInApplyList = 9024,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialBlackListFull = 9031,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialInBlackList = 9032,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialNotInBlackList = 9033,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialInTargetBlackList = 9034,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialDailyApplyLimit = 9051,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialDailyGiftRecvLimit = 9052,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialDailyGiftSendLimit = 9053,
    /// <summary>
    /// 好友系统
    /// </summary>
    KCserrorSocialDailyInformLimit = 9054,
    /// <summary>
    /// Max
    /// </summary>
    KCserrorCodeMax = 9055,
  }

  #endregion

}

#endregion Designer generated code
