// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cspushgift.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::ILRuntime.Protobuf;
using pbc = global::ILRuntime.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Csp {

  #region Messages
  /// <summary>
  ///========== proto define ==========
  /// </summary>
  public sealed class CSPushGiftPullReq : pb::IMessage {
    private static readonly pb::MessageParser<CSPushGiftPullReq> _parser = new pb::MessageParser<CSPushGiftPullReq>(() => new CSPushGiftPullReq());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSPushGiftPullReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed class CSPushGiftPullResp : pb::IMessage {
    private static readonly pb::MessageParser<CSPushGiftPullResp> _parser = new pb::MessageParser<CSPushGiftPullResp>(() => new CSPushGiftPullResp());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSPushGiftPullResp> Parser { get { return _parser; } }

    /// <summary>Field number for the "gift" field.</summary>
    public const int GiftFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Datap.PushGiftItem> _repeated_gift_codec
        = pb::FieldCodec.ForMessage(10, global::Datap.PushGiftItem.Parser);
    private readonly pbc::RepeatedField<global::Datap.PushGiftItem> gift_ = new pbc::RepeatedField<global::Datap.PushGiftItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Datap.PushGiftItem> Gift {
      get { return gift_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      gift_.WriteTo(output, _repeated_gift_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += gift_.CalculateSize(_repeated_gift_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            gift_.AddEntriesFrom(input, _repeated_gift_codec);
            break;
          }
        }
      }
    }

  }

  public sealed class CSPushGiftDelNotify : pb::IMessage {
    private static readonly pb::MessageParser<CSPushGiftDelNotify> _parser = new pb::MessageParser<CSPushGiftDelNotify>(() => new CSPushGiftDelNotify());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CSPushGiftDelNotify> Parser { get { return _parser; } }

    /// <summary>Field number for the "gift" field.</summary>
    public const int GiftFieldNumber = 1;
    private global::Datap.PushGiftItem gift_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Datap.PushGiftItem Gift {
      get { return gift_; }
      set {
        gift_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (gift_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Gift);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (gift_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Gift);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (gift_ == null) {
              gift_ = new global::Datap.PushGiftItem();
            }
            input.ReadMessage(gift_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
